swagger: '2.0'
info:
  version: 1.0.0
  title: Digital Citizenship API
  contact:
    name: Digital Transformation Team and AgID
    url: https://forum.italia.it/c/progetto-io
  x-logo:
    url: https://io.italia.it/assets/img/io-logo-blue.svg

host: api.cd.italia.it
tags:
  - name: public
    description: Public APIs
  - name: restricted
    description: Restricted APIs
x-tagGroups:
  - name: For Public Administrations and services
    tags:
      - public
  - name: For the IO app
    tags:
      - restricted
basePath: "/api/v1"
schemes:
- https
security:
- SubscriptionKey: []
paths:
  "/messages/{fiscal_code}/{id}":
    get:
      tags:
        - public
        - restricted
      operationId: getMessage
      summary: Get Message
      description: |-
        The previously created message with the provided message ID is
        returned.
      parameters:
      - $ref: "#/parameters/FiscalCode"
      - name: id
        in: path
        type: string
        required: true
        description: The ID of the message.
      responses:
        '200':
          description: Message found.
          schema:
            $ref: "#/definitions/MessageResponseWithContent"
          examples:
            application/json:
              message:
                id: 01BX9NSMKAAAS5PSP2FATZM6BQ
                fiscal_code: QXJNTX9RCRVD6V4O
                time_to_live: 3600
                content:
                  subject: message subject, aliquip sint nulla in estinut
                  markdown:  |-
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas et mollis felis.
                    Vivamus orci nisl, commodo ut sodales ut, eleifend a libero. Donec dapibus, turpis in mattis tempor,
                    risus nunc malesuada ex, non aliquet metus nunc a lacus. Aenean in arcu vitae nisl porta
                    fermentum nec non nibh. Phasellus tortor tellus, semper in metus eget, eleifend
                    laoreet nibh. Aenean feugiat lectus ut nisl eleifend gravida.
                sender_service_id: 01BX9NSMKVXXS5PSP2FATZM6QX
              notification:
                email: QUEUED
        '401':
          description: Unauthorized
        '404':
          description: No message found for the provided ID.
          schema:
            $ref: "#/definitions/ProblemJson"
        '429':
          description: Too many requests
definitions:
  ProblemJson:
   $ref: "definitions.yaml#/ProblemJson"
  MessageResponseWithContent:
    $ref: "definitions.yaml#/MessageResponseWithContent"
  
responses: {}
parameters:
  PaginationRequest:
    name: cursor
    in: query
    type: string
    minimum: 1
    description: An opaque identifier that points to the next item in the collection.
    x-example: 01BX9NSMKVXXS5PSP2FATZM123
  FiscalCode:
    name: fiscal_code
    in: path
    type: string
    maxLength: 16
    minLength: 16
    required: true
    description: The fiscal code of the user, all upper case.
    pattern: "[A-Z]{6}[0-9LMNPQRSTUV]{2}[ABCDEHLMPRST][0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{3}[A-Z]"
    x-example: SPNDNL80R13C555X
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  SubscriptionKey:
    type: apiKey
    name: Ocp-Apim-Subscription-Key
    in: header
    description: The API key obtained through the developer portal.
